# frozen_string_literal: true

##
# EmailTemplate module for generating monthly location summary emails
module EmailTemplate
  def self.generate(summary)
    <<~HTML
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
          }
          .container {
            background: white;
            border-radius: 10px;
            overflow: hidden;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
          }
          .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            text-align: center;
          }
          .header h1 {
            margin: 0 0 10px 0;
            font-size: 28px;
          }
          .header p {
            margin: 0;
            opacity: 0.9;
            font-size: 16px;
          }
          .content {
            padding: 30px;
          }
          .calendar {
            display: grid;
            gap: 10px;
            margin-top: 20px;
          }
          .day-card {
            background: #f8f9fa;
            border-left: 4px solid #667eea;
            padding: 15px;
            border-radius: 5px;
            transition: all 0.2s;
          }
          .day-card:hover {
            background: #e9ecef;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
          }
          .day-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 10px;
          }
          .day-date {
            font-weight: 600;
            color: #2d3748;
            font-size: 16px;
          }
          .day-count {
            font-size: 12px;
            color: #718096;
            background: #e2e8f0;
            padding: 2px 8px;
            border-radius: 12px;
          }
          .day-locations {
            color: #4a5568;
            font-size: 14px;
            line-height: 1.8;
          }
          .location-item {
            display: inline-block;
            margin-right: 8px;
            margin-bottom: 4px;
          }
          .stats {
            background: #f7fafc;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
            text-align: center;
          }
          .stat-number {
            font-size: 36px;
            font-weight: bold;
            color: #667eea;
          }
          .stat-label {
            color: #718096;
            font-size: 14px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
          }
          .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #e2e8f0;
            color: #718096;
            font-size: 12px;
            text-align: center;
          }
          .empty-day {
            opacity: 0.5;
            font-style: italic;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>📍 Monthly Location Summary</h1>
            <p>#{summary[:end_time].strftime('%B %Y')}</p>
          </div>

          <div class="content">
            <div class="stats">
              <div class="stat-number">#{summary[:daily_summaries].length}</div>
              <div class="stat-label">Days with Location Data</div>
            </div>

            <h2 style="color: #2d3748; margin-bottom: 20px;">Daily Location History</h2>
            <div class="calendar">
              #{calendar_html(summary[:daily_summaries])}
            </div>

            <div class="footer">
              <p>🤖 Generated by Location Tracker</p>
              <p>#{summary[:start_time].strftime('%B %d')} - #{summary[:end_time].strftime('%B %d, %Y')}</p>
            </div>
          </div>
        </div>
      </body>
      </html>
    HTML
  end

  def self.generate_text(summary)
    text = <<~TEXT
      MONTHLY LOCATION SUMMARY
      #{summary[:end_time].strftime('%B %Y')}

      Days with Location Data: #{summary[:daily_summaries].length}

      Daily Location History:

    TEXT

    summary[:daily_summaries].reverse.each do |day|
      text += "\n#{day[:date].strftime('%a, %b %d')} (#{day[:visit_count]} points)\n"
      if day[:locations].empty?
        text += "  No location data\n"
      else
        day[:locations].each do |location|
          text += "  • #{location}\n"
        end
      end
    end

    text += "\n---\n"
    text += "Generated by Location Tracker\n"
    text += "#{summary[:start_time].strftime('%B %d')} - #{summary[:end_time].strftime('%B %d, %Y')}\n"

    text
  end

  def self.calendar_html(daily_summaries)
    return '<p class="empty-day">No location data available</p>' if daily_summaries.empty?

    # Reverse to show most recent first
    daily_summaries.reverse.map do |day|
      <<~HTML
        <div class="day-card">
          <div class="day-header">
            <div class="day-date">#{format_day_date(day[:date])}</div>
            <div class="day-count">#{day[:visit_count]} points</div>
          </div>
          <div class="day-locations">
            #{format_locations(day[:locations])}
          </div>
        </div>
      HTML
    end.join("\n")
  end

  def self.format_day_date(date)
    today = Date.today
    yesterday = today - 1

    if date == today
      "Today - #{date.strftime('%B %d')}"
    elsif date == yesterday
      "Yesterday - #{date.strftime('%B %d')}"
    else
      date.strftime('%A, %B %d')
    end
  end

  def self.format_locations(locations)
    if locations.empty?
      '<span class="empty-day">No location data</span>'
    else
      locations.map do |location|
        "<span class=\"location-item\">#{location}</span>"
      end.join(' • ')
    end
  end
end
