# frozen_string_literal: true

##
# EmailTemplate module for generating daily summary emails
module EmailTemplate
  def self.generate(summary)
    <<~HTML
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
          }
          .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 30px;
          }
          .header h1 {
            margin: 0 0 10px 0;
            font-size: 28px;
          }
          .header p {
            margin: 0;
            opacity: 0.9;
            font-size: 16px;
          }
          .stat-card {
            background: #f7fafc;
            border-left: 4px solid #667eea;
            padding: 20px;
            margin-bottom: 20px;
            border-radius: 5px;
          }
          .stat-number {
            font-size: 36px;
            font-weight: bold;
            color: #667eea;
            margin: 10px 0;
          }
          .stat-label {
            color: #718096;
            font-size: 14px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
          }
          .location-list {
            margin-top: 30px;
          }
          .location-item {
            background: white;
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            padding: 15px;
            margin-bottom: 10px;
          }
          .location-name {
            font-size: 18px;
            font-weight: 600;
            color: #2d3748;
            margin-bottom: 5px;
          }
          .location-meta {
            color: #718096;
            font-size: 14px;
          }
          .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e2e8f0;
            color: #718096;
            font-size: 12px;
            text-align: center;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>📍 Daily Location Summary</h1>
          <p>#{summary[:start_time].strftime('%B %d, %Y')}</p>
        </div>

        <div class="stat-card">
          <div class="stat-label">Total Locations Captured</div>
          <div class="stat-number">#{summary[:total_locations]}</div>
        </div>

        #{summary[:primary_location] ? primary_location_html(summary[:primary_location]) : ''}

        <div class="location-list">
          <h2 style="color: #2d3748; margin-bottom: 20px;">Places Visited</h2>
          #{locations_html(summary[:locations_visited])}
        </div>

        <div class="footer">
          <p>🤖 Generated by Location Tracker</p>
          <p>Tracking period: #{summary[:start_time].strftime('%I:%M %p')} - #{summary[:end_time].strftime('%I:%M %p PT')}</p>
        </div>
      </body>
      </html>
    HTML
  end

  def self.generate_text(summary)
    text = <<~TEXT
      DAILY LOCATION SUMMARY
      #{summary[:start_time].strftime('%B %d, %Y')}

      Total Locations Captured: #{summary[:total_locations]}

    TEXT

    if summary[:primary_location]
      text += <<~TEXT
        Primary Location: #{summary[:primary_location][:name]}
        Visits: #{summary[:primary_location][:visit_count]}

      TEXT
    end

    text += "Places Visited:\n\n"

    summary[:locations_visited].each do |location|
      text += "• #{location[:name]} - #{location[:visit_count]} visits\n"
    end

    text += "\n---\n"
    text += "Generated by Location Tracker\n"
    text += "Tracking period: #{summary[:start_time].strftime('%I:%M %p')} - #{summary[:end_time].strftime('%I:%M %p PT')}\n"

    text
  end

  def self.primary_location_html(location)
    <<~HTML
      <div class="stat-card" style="border-left-color: #48bb78;">
        <div class="stat-label">Primary Location</div>
        <div style="font-size: 24px; font-weight: 600; color: #2d3748; margin: 10px 0;">
          #{location[:name]}
        </div>
        <div class="location-meta">
          #{location[:visit_count]} visits
        </div>
      </div>
    HTML
  end

  def self.locations_html(locations)
    return '<p style="color: #718096;">No locations recorded during this period.</p>' if locations.empty?

    locations.map do |location|
      <<~HTML
        <div class="location-item">
          <div class="location-name">#{location[:name]}</div>
          <div class="location-meta">
            #{location[:visit_count]} visits •
            #{location[:first_seen].strftime('%I:%M %p')} - #{location[:last_seen].strftime('%I:%M %p')}
          </div>
        </div>
      HTML
    end.join("\n")
  end
end
